version: '2'
services:
  db:
    image: postgres:10
    container_name: db
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Belfast
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Secret1
      - POSTGRES_DB=app
  api:
    image: crystallang/crystal:0.33.0-alpine
    container_name: api
    depends_on:
      - db
    restart: always
    volumes:
      - "./:/app"
    working_dir: /app
    command: crystal run ./src/todo_api.cr
    ports:
      - "80:3000"
      - "3000:3000"
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:Secret1@db:5432/app
      - KEMAL_ENV=development
      - DEBUG=1
