version: '2'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Belfast
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Secret1
      - POSTGRES_DB=app
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./pgdata:/var/lib/postgresql/data"
  # app:
  #   image: alpine:latest
  #   container_name: app
  #   depends_on:
  #     - postgres
  #   working_dir: /app
  #   command: ./todo_api
  #   ports:
  #     - "80:3000"
  #     - "3000:3000"
  #   volumes:
  #     - "./bin:/app"
