version: '2'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Belfast
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Secret1
      - POSTGRES_DB=app
  api:
    image: crystallang/crystal:latest-alpine
    container_name: api
    depends_on:
      - postgres
    restart: always
    volumes:
      - "./:/app"
    working_dir: /app
    command: crystal run ./src/todo_api.cr
    ports:
      - "80:3000"
      - "3000:3000"
