# Login as 'todo.checklist@yahoo.com', copy the token from the browser and set in .env
@token = {{$dotenv JWT_TOKEN}}
@api = http://localhost:8080


### Health Check
GET {{api}}/health


### Get Session
GET {{api}}/session
Authorization: {{token}}
Accept: application/json


### Create List
POST {{api}}/list
Authorization: {{token}}
Accept: application/json
Content-Type: application/json

{
  "list": {
    "name": "Test List {{$guid}}",
    "todos": [
      { "name": "Wash Car", "done": false },
      { "name": "Play Records", "done": true },
      { "name": "Watch The Bikes", "done": false },
      { "name": "Write Code", "done": true },
      { "name": "Netflix & Chill", "done": false }
    ],
    "additional_users": [
      "michael.telford@live.com"
    ]
  }
}


### Get Lists
# @name lists
GET {{api}}/lists
Authorization: {{token}}
Accept: application/json
Accept-Encoding: gzip


### Get List By ID
# @name list
GET {{api}}/list/{{lists.response.body.lists[0].id}}
Authorization: {{token}}
Accept: application/json
Accept-Encoding: gzip


### Update List
# @name list
PUT {{api}}/list/{{lists.response.body.lists[0].id}}
Authorization: {{token}}
Accept: application/json
Content-Type: application/json

{
  "list": {
    "name": "Test List {{$guid}}",
    "todos": [
      { "name": "Wash Car", "done": true },
      { "name": "Play Records", "done": true },
      { "name": "Watch The Bikes", "done": true },
      { "name": "Write Code", "done": true },
      { "name": "Netflix & Chill", "done": false }
    ],
    "additional_users": []
  }
}


### Delete List
DELETE {{api}}/list/{{lists.response.body.lists[0].id}}
Authorization: {{token}}
