CREATE TABLE IF NOT EXISTS list (
  id SERIAL NOT NULL PRIMARY KEY,
  user_email TEXT NOT NULL,
  user_name TEXT NULL,
  name TEXT NOT NULL,
  todos JSON NOT NULL,
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
